/**
 * Reads dist/figma/variables-manifest.json and generates self-contained
 * Figma Plugin API JavaScript files (one per collection) that can be
 * executed via MCP `use_figma` or `figma_execute`.
 *
 * Output: dist/figma/sync-{NN}-{collection-slug}.js
 *
 * Collections are numbered to enforce execution order — Foundation must
 * be created before Color mode so cross-collection aliases resolve.
 *
 * Usage:
 *   bun run scripts/figma-sync-code.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const DIST_DIR = resolve(import.meta.dirname, '../dist/figma')
const manifest = JSON.parse(readFileSync(resolve(DIST_DIR, 'variables-manifest.json'), 'utf-8'))

interface FigmaVariable {
  name: string
  type: string
  description?: string
  values: Record<string, unknown>
}

interface FigmaCollection {
  name: string
  modes: string[]
  variables: FigmaVariable[]
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/\s+/g, '-')
}

function isAlias(value: unknown): value is { alias: string } {
  return typeof value === 'object' && value !== null && 'alias' in value
}

/**
 * Scope mapping function — embedded in generated code so Figma variables
 * are scoped to the correct property pickers.
 */
const SCOPE_MAP_CODE = `
function getScopes(name) {
  var g = name.split("/")[0];
  var map = {
    colors: ["ALL_FILLS", "STROKE_COLOR", "EFFECT_COLOR"],
    spacing: ["GAP"],
    sizes: ["WIDTH_HEIGHT"],
    containerSizes: ["WIDTH_HEIGHT"],
    breakpoints: ["WIDTH_HEIGHT"],
    radii: ["CORNER_RADIUS"],
    borderWidths: ["STROKE_FLOAT"],
    blurs: ["EFFECT_FLOAT"],
    opacity: ["OPACITY"],
    fonts: ["FONT_FAMILY"],
    fontSizes: ["FONT_SIZE"],
    fontWeights: ["FONT_WEIGHT"],
    lineHeights: ["LINE_HEIGHT"],
    letterSpacings: ["LETTER_SPACING"],
    durations: [],
    zIndex: []
  };
  return map[g] || [];
}`

function generateDirectValueCollection(col: FigmaCollection): string {
  const modeName = col.modes[0]!

  const entries = col.variables.map((v) => {
    const row: unknown[] = [v.name, v.type, v.values[modeName!]]
    if (v.description) row.push(v.description)
    return row
  })

  return `// Sync ${col.name} collection (${col.variables.length} variables)
// Generated by scripts/figma-sync-code.ts — do not edit
${SCOPE_MAP_CODE}

var COLLECTION = ${JSON.stringify(col.name)};
var MODE = ${JSON.stringify(modeName)};
var VARS = ${JSON.stringify(entries)};

var col = (await figma.variables.getLocalVariableCollectionsAsync()).find(function(c) { return c.name === COLLECTION; });
if (!col) {
  col = figma.variables.createVariableCollection(COLLECTION);
}

var mode = col.modes.find(function(m) { return m.name === MODE; });
if (!mode) {
  if (col.modes.length === 1 && col.modes[0].name !== MODE) {
    col.renameMode(col.modes[0].modeId, MODE);
    mode = { modeId: col.modes[0].modeId, name: MODE };
  } else {
    var newModeId = col.addMode(MODE);
    mode = { modeId: newModeId, name: MODE };
  }
}

var existing = {};
var allVars = await figma.variables.getLocalVariablesAsync();
for (var vi = 0; vi < allVars.length; vi++) {
  if (allVars[vi].variableCollectionId === col.id) existing[allVars[vi].name] = allVars[vi];
}

var created = 0, updated = 0;
for (var ei = 0; ei < VARS.length; ei++) {
  var entry = VARS[ei];
  var name = entry[0];
  var type = entry[1];
  var val = entry[2];
  var desc = entry.length > 3 ? entry[3] : undefined;

  var v = existing[name];
  if (!v) {
    v = figma.variables.createVariable(name, col, type);
    created++;
  } else {
    updated++;
  }
  v.setValueForMode(mode.modeId, val);
  v.scopes = getScopes(name);
  v.setVariableCodeSyntax("WEB", "var(--reva-" + name.replace(/\\//g, "-") + ")");
  if (desc) v.description = desc;
}

return COLLECTION + ": " + created + " created, " + updated + " updated (" + VARS.length + " total)";`
}

function generateAliasCollection(col: FigmaCollection): string {
  const entries = col.variables.map((v) => {
    const row: unknown[] = [v.name, v.type]
    for (const modeName of col.modes) {
      const val = v.values[modeName]
      row.push(isAlias(val) ? val.alias : val)
    }
    if (v.description) row.push(v.description)
    return row
  })

  return `// Sync ${col.name} collection (${col.variables.length} variables)
// Generated by scripts/figma-sync-code.ts — do not edit
${SCOPE_MAP_CODE}

var COLLECTION = ${JSON.stringify(col.name)};
var MODES = ${JSON.stringify(col.modes)};
var VARS = ${JSON.stringify(entries)};

var allCollections = await figma.variables.getLocalVariableCollectionsAsync();

// Build collection name lookup
var colByName = {};
for (var ci = 0; ci < allCollections.length; ci++) colByName[allCollections[ci].name] = allCollections[ci];

// Build variable lookup: "CollectionName/varName" → variable
var varLookup = {};
var allVarsForLookup = await figma.variables.getLocalVariablesAsync();
for (var vi = 0; vi < allVarsForLookup.length; vi++) {
  var vr = allVarsForLookup[vi];
  for (var cj = 0; cj < allCollections.length; cj++) {
    if (allCollections[cj].id === vr.variableCollectionId) {
      varLookup[allCollections[cj].name + "/" + vr.name] = vr;
      break;
    }
  }
}

var col = colByName[COLLECTION];
if (!col) {
  col = figma.variables.createVariableCollection(COLLECTION);
}

var modeIds = [];
for (var mi = 0; mi < MODES.length; mi++) {
  var mode = col.modes.find(function(m) { return m.name === MODES[mi]; });
  if (!mode) {
    if (mi === 0 && col.modes.length === 1 && MODES.indexOf(col.modes[0].name) === -1) {
      col.renameMode(col.modes[0].modeId, MODES[mi]);
      mode = { modeId: col.modes[0].modeId, name: MODES[mi] };
    } else {
      var newModeId = col.addMode(MODES[mi]);
      mode = { modeId: newModeId, name: MODES[mi] };
    }
  }
  modeIds.push(mode.modeId);
}

var existing = {};
var allLocalVars = await figma.variables.getLocalVariablesAsync();
for (var xi = 0; xi < allLocalVars.length; xi++) {
  if (allLocalVars[xi].variableCollectionId === col.id) existing[allLocalVars[xi].name] = allLocalVars[xi];
}

var created = 0, updated = 0, aliasErrors = 0;
for (var ei = 0; ei < VARS.length; ei++) {
  var entry = VARS[ei];
  var name = entry[0];
  var type = entry[1];
  var desc = entry.length > 2 + MODES.length ? entry[2 + MODES.length] : undefined;

  var v = existing[name];
  if (!v) {
    v = figma.variables.createVariable(name, col, type);
    created++;
  } else {
    updated++;
  }

  for (var fi = 0; fi < MODES.length; fi++) {
    var val = entry[2 + fi];
    if (typeof val === "string" && val.indexOf("/") !== -1) {
      var target = varLookup[val];
      if (target) {
        v.setValueForMode(modeIds[fi], figma.variables.createVariableAlias(target));
      } else {
        aliasErrors++;
      }
    } else {
      v.setValueForMode(modeIds[fi], val);
    }
  }
  v.scopes = getScopes(name);
  v.setVariableCodeSyntax("WEB", "var(--reva-" + name.replace(/\\//g, "-") + ")");
  if (desc) v.description = desc;
}

var msg = COLLECTION + ": " + created + " created, " + updated + " updated (" + VARS.length + " total)";
if (aliasErrors > 0) msg += " \\u26A0 " + aliasErrors + " alias(es) not resolved";
return msg;`
}

const collections: FigmaCollection[] = manifest.collections

for (let i = 0; i < collections.length; i++) {
  const col = collections[i] as FigmaCollection
  const num = String(i + 1).padStart(2, '0')
  const slug = slugify(col.name)

  const hasAliases = col.variables.some((v) => Object.values(v.values).some(isAlias))

  const code = hasAliases ? generateAliasCollection(col) : generateDirectValueCollection(col)

  const outPath = resolve(DIST_DIR, `sync-${num}-${slug}.js`)
  writeFileSync(outPath, code)
  console.log(`✓ Generated ${outPath} (${col.variables.length} variables)`)
}
